version: "3.7"
services: 
  backend:
        image: 'nginx:stable-alpine'
        build:
          context: ./backend
          dockerfile: dockerfiles/nginx.dockerfile
        ports:
          - '127.0.0.1:9000:80'
        #comment out volumes for deployment ready  
        volumes:
          - ./backend/src:/var/www/html
          - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - php
          # - mysql
  php:
        build: 
          context: ./backend
          dockerfile: dockerfiles/php.dockerfile
        #comment out volumes for deployment ready  
        volumes:
          - ./backend/src:/var/www/html:delegated
  # mysql:
  #       platform: linux/x86_64
  #       image: mysql:5.7
  #       env_file:
  #           - ./backend/env/mysql.env
  frontend:
    build: ./frontend
    ports:
      - '127.0.0.1:3000:8081'
    volumes:
      - ./frontend/src:/app/src #bind mount
    stdin_open: true
    tty: true
    env_file:
      - ./env/frontend.env
    depends_on:
      - backend
volumes: #only named volumes here
  data: