# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Install, Build, Test Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        shard: [1/3, 2/3, 3/3]
        

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        #cache: 'npm'
        #cache-dependency-path: "**/package-lock.json"
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build --if-present
    # Add persistance between CI runs
    - name: Cache Jest cache
      uses: actions/cache@v3
      with:
        path: /tmp/jest_rt
        key: ${{ hashFiles('**/package-lock.json') }}
    
    - name: Test
      run: npm test -- --maxWorkers=2 --shard=${{ matrix.shard }}
      # use both available cores and splitting workflow across additional vms
